[package]
name = "lambda_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.7.3"
serde = "1.0.159"
tokio = "1.27.0"

[dev-dependencies]
maplit = "1.0.2"